name: ⏱️ Trigger RAG CRON automatisch

on:
  schedule:
    - cron: "*/5 * * * *"  # Elke 5 minuten (UTC)
  workflow_dispatch:        # Handmatig draaien in GitHub

jobs:
  trigger-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call RAG CRON endpoint
        run: |
          curl -X GET "https://fullforce-private-ai-agent.vercel.app/api/cron/process-unindexed-documents?key=${{ secrets.CRON_API_KEY }}" \
               -H "x-cron-key: ${{ secrets.CRON_BYPASS_KEY }}" \
               -H "x-api-key: ${{ secrets.CRON_API_KEY }}"
