name: run-ocr
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  ocr:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 18 }
      - name: Sanity secrets
        run: |
          [ -n "${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" ] || (echo "❌ NEXT_PUBLIC_SUPABASE_URL missing"; exit 1)
          [ -n "${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" ] || (echo "❌ SUPABASE_SERVICE_ROLE_KEY missing"; exit 1)
          echo "✅ secrets ok"
      - name: List OCR-needed docs
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: node scripts/list-ocr-needed.mjs || true
      - name: Run OCR for 1 doc
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: node scripts/ocr-runner.mjs --limit=1
