# Scheduled trigger for cron endpoint using header auth
name: trigger-cron

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

concurrency:
  group: trigger-cron
  cancel-in-progress: false

jobs:
  trigger:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Guard – block query-key usage
        run: |
          set -euo pipefail
          if grep -R --include="*.yml" -nE '\?key=' .github/workflows/; then
            echo "❌ Found deprecated ?key= usage in workflows"; exit 1;
          fi
          echo "✅ No query-key usage found"
      - name: Check required secrets
        run: |
          set -euo pipefail
          [ -n "${{ secrets.OPENAI_API_KEY }}" ] || (echo "❌ OPENAI_API_KEY missing"; exit 1)
          [ -n "${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" ] || (echo "❌ SUPABASE_SERVICE_ROLE_KEY missing"; exit 1)
          [ -n "${{ secrets.CRON_API_KEY }}" ] || (echo "❌ CRON_API_KEY missing"; exit 1)
          echo "✅ Secrets present"
      - name: Trigger cron endpoint (header auth, limit=1)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          set -euo pipefail
          curl -sS -f --retry 3 --retry-delay 5 \
            -H "x-api-key: ${{ secrets.CRON_API_KEY }}" \
            "https://fullforce-private-ai-agent.vercel.app/api/cron/process-unindexed-documents?limit=1"

