name: trigger-cron

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Guard – block query-key usage
        run: |
          set -euo pipefail
          if grep -R --include="*.yml" -nE '\?key=' .github/workflows/; then
            echo "❌ Found deprecated ?key= usage in workflows"; exit 1;
          fi
          echo "✅ No query-key usage found"
      - name: Trigger cron endpoint
        run: |
          curl -sS -f --retry 3 --retry-delay 5 \
            -H "X-Cron-Key: ${{ secrets.CRON_BYPASS_KEY }}" \
            "https://fullforce-private-ai-agent.vercel.app/api/cron/process-unindexed-documents"
